/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "database.h"

bool_t
xdr_db_args (XDR *xdrs, db_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->DB_TYPE))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->DB_NAME, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
